# Standards: 0.1
---
- name: Fact spotify user
  set_fact:
    spotify_user: "{{ spotify_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - spotify

- become: "{{ (spotify_user != ansible_user_id) | bool }}"
  become_user: "{{ spotify_user }}"
  block:
    - name: Install required package
      ignore_errors: True
      homebrew_cask:
        name: spotify
        greedy: True
        options: appdir=/Applications
        accept_external_apps: False
        state: upgraded
      tags:
        - spotify

- name: Remove quarantine flag
  register: spotify_quarantine
  failed_when: spotify_quarantine.rc != 0 and "No such xattr" not in spotify_quarantine.stderr
  changed_when: spotify_quarantine.rc == 0
  command: xattr -d com.apple.quarantine /Applications/Spotify.app
  tags:
    - spotify

...
