# Standards: 0.1
---
- name: Kill spotify
  command: killall Spotify
  register: spotify_kill
  failed_when: spotify_kill.rc != 0 and "No matching processes belonging to you were found" not in spotify_kill.stderr
  become: "{{ (spotify_user != ansible_user_id) | bool }}"
  become_user: "{{ spotify_user }}"

- name: Start spotify
  when: spotify_started
  command: open -j /Applications/Spotify.app
  become: "{{ (spotify_user != ansible_user_id) | bool }}"
  become_user: "{{ spotify_user }}"

...
